name: Intake Guide for Issues
description: A guide to help you define the Definition of Done for an issue in the Synapse Team
labels: ["support request", "request ai review"]
projects:
  - github/21922 # Synapse Roadmap
body:
  - type: markdown
    attributes:
      value: |
        A standardized template for the Definition of Done (DoD) to guide engineers in creating issues with clear and measurable completion criteria.
        This template is typically used for larger batch work type of issues.
  - type: textarea
    id: summary
    attributes:
      label: "⚒️ Summary"
      description: "TL;DR summary of the request."
      placeholder: ex. This issue outlines a project designed to enhance the Fundamentals program by addressing current tooling limitations...
    validations:
      required: true
  - type: textarea
    id: problemStatement
    attributes:
      label: "🚩 Problem Statement"
      description: "What is the specific issue or challenge that needs to be addressed?"
      placeholder: ex. Currently, the biggest hurdle blocking progress in the Fundamentals program is the lack of adequate tooling...
    validations:
      required: true
  - type: textarea
    id: proposedSolution
    attributes:
      label: "💡 Proposed Solution"
      description: How will this issue be resolved? What actions are required to address the problem?
      placeholder: ex. We propose to invest in and develop interim tooling solutions that will support the Fundamentals program...
    validations:
      required: true
  - type: textarea
    id: definitionOfDone
    attributes:
      label: "✅ Definition of Done"
      description: "Clear and measurable success metric or deliverable"
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
