name: AI Issue Assessment

on:
  issues:
    types:
      - labeled

jobs:
  assess:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Run AI assessment for issue labeled
        if: github.event.label.name == env.ai_review_label
        id: ai-assessment-issue-labeled
        uses: ./action
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_tokens: '2000'
          ai_review_label: 'request ai review'
          prompts_directory: '.github/prompts'
          labels_to_prompts_mapping: 'bug,bug-review.prompt.yml|support request,request-intake.prompt.yml'
